services:
  app-alpha:
    image: alpine
    container_name: container-alpha
    tty: true
    volumes:
      - shared-storage:/data/shared

  app-beta:
    image: alpine
    container_name: container-beta
    tty: true
    volumes:
      - shared-storage:/data/shared

volumes:
  shared-storage:
    driver: local