services:
  web-server:
    image: nginx:alpine
    container_name: log-demo-nginx
    ports:
      - "8080:80"
    volumes:
      # ホストの ./logs フォルダを コンテナの nginxログ保存先にマウント
      - ./logs:/var/log/nginx